version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bjj-champ
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bjj-network

  app:
    network_mode: host
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: localhost
      DB_PORT: 5433
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: bjj-champ
    # networks:
    #   - bjj-network

networks:
  bjj-network:
    driver: bridge

volumes:
  postgres_data: